In [1]:
import pandas as pd
import numpy as np
from scipy.stats import norm


data = pd.read_csv('8k_with_prices.csv')
data

,Date,Ticker,Close,Filing Date,Market,Ret,Items
0,2019-12-31,AA,21.144423,2020-01-15,0.002946,NaN,"2.02,9.01"
1,2020-01-02,AA,21.055950,2020-01-15,0.008379,-0.012563,"2.02,9.01"
2,2020-01-03,AA,21.134588,2020-01-15,-0.007060,0.010795,"2.02,9.01"
3,2020-01-06,AA,20.643089,2020-01-15,0.003533,-0.026789,"2.02,9.01"
4,2020-01-07,AA,20.957651,2020-01-15,-0.002803,0.018041,"2.02,9.01"
...,...,...,...,...,...,...,...
527599,2022-11-09,ZI,28.070000,2022-11-01,-0.020778,-0.026081,"2.02,9.01"
527600,2022-11-10,ZI,30.940001,2022-11-01,0.055434,0.046810,"2.02,9.01"
527601,2022-11-11,ZI,32.560001,2022-11-01,0.009241,0.043119,"2.02,9.01"
527602,2022-11-14,ZI,31.340000,2022-11-01,-0.008936,-0.028534,"2.02,9.01"
527603,2022-11-15,ZI,31.690001,2022-11-01,0.008713,0.002455,"2.02,9.01"

In [2]:
# 将 'Filing Date' 和 'Date' 列的数据类型转换为日期时间
data['Filing Date'] = pd.to_datetime(data['Filing Date'])
data['Date'] = pd.to_datetime(data['Date'])
data

             Date Ticker      Close Filing Date    Market       Ret      Items
0      2019-12-31     AA  21.144423  2020-01-15  0.002946       NaN  2.02,9.01
1      2020-01-02     AA  21.055950  2020-01-15  0.008379 -0.012563  2.02,9.01
2      2020-01-03     AA  21.134588  2020-01-15 -0.007060  0.010795  2.02,9.01
3      2020-01-06     AA  20.643089  2020-01-15  0.003533 -0.026789  2.02,9.01
4      2020-01-07     AA  20.957651  2020-01-15 -0.002803  0.018041  2.02,9.01
...           ...    ...        ...         ...       ...       ...        ...
527599 2022-11-09     ZI  28.070000  2022-11-01 -0.020778 -0.026081  2.02,9.01
527600 2022-11-10     ZI  30.940001  2022-11-01  0.055434  0.046810  2.02,9.01
527601 2022-11-11     ZI  32.560001  2022-11-01  0.009241  0.043119  2.02,9.01
527602 2022-11-14     ZI  31.340000  2022-11-01 -0.008936 -0.028534  2.02,9.01
527603 2022-11-15     ZI  31.690001  2022-11-01  0.008713  0.002455  2.02,9.01

[527604 rows x 7 columns]

In [3]:
# 筛选出 'Filing Date' 和 'Date' 相同的数据
filtered_data = data[data['Filing Date'].dt.date == data['Date'].dt.date]
# 删除 'Date' 列
filtered_data = filtered_data.drop(columns=['Date','Close'])
# 按 Ticker 和 Filing Date 进行排序
filtered_data = filtered_data.sort_values(by=['Ticker', 'Filing Date'])
# 删除重复数据
filtered_data = filtered_data.drop_duplicates(subset=['Ticker', 'Filing Date', 'Items'])
# 将 Section 按逗号拆分并计算其长度
filtered_data['Section_Length'] = filtered_data['Items'].str.split(',').str.len()
# 找到每个 Ticker 和 Filing Date 组合下 Section 最长的长度
max_section_lengths = filtered_data.groupby(['Ticker', 'Filing Date'])['Section_Length'].transform('max')
# 保留 Section 最长的数据
filtered_data = filtered_data[filtered_data['Section_Length'] == max_section_lengths]
# 删除 Section_Length 列
filtered_data.drop('Section_Length', axis=1, inplace=True)
# 重新设置索引
filtered_data = filtered_data.reset_index(drop=True)
# 打印筛选后的数据
print(filtered_data)

      Ticker Filing Date    Market       Ret                     Items
0         AA  2020-01-15  0.001870 -0.011198                 2.02,9.01
1         AA  2020-02-03  0.007255  0.013534                 8.01,9.01
2         AA  2020-04-22  0.022930  0.008491  1.01,2.02,2.03,8.01,9.01
3         AA  2020-05-11  0.000133 -0.037308                      5.07
4         AA  2020-06-25  0.010959  0.050980            1.01,2.03,9.01
...      ...         ...       ...       ...                       ...
25100     ZI  2022-05-02  0.005675  0.032299                 2.02,9.01
25101     ZI  2022-05-19 -0.005834 -0.021573       3.03,5.03,5.07,9.01
25102     ZI  2022-06-30 -0.008759 -0.019027            5.02,7.01,9.01
25103     ZI  2022-08-01 -0.002823 -0.001400                 2.02,9.01
25104     ZI  2022-11-01 -0.004101 -0.019029                 2.02,9.01

[25105 rows x 5 columns]

In [4]:
# 遍历每行数据，根据 Section 设置对应的列为1
for index, row in filtered_data.iterrows():
    sections = row['Items'].split(',')
    for section in sections:
        column_name = section
        if column_name not in filtered_data.columns:
            filtered_data[column_name] = 0
        filtered_data.at[index, column_name] = 1

# 打印筛选后的数据（包括新创建的列）
print(filtered_data)

      Ticker Filing Date    Market       Ret                     Items  2.02  \
0         AA  2020-01-15  0.001870 -0.011198                 2.02,9.01     1
1         AA  2020-02-03  0.007255  0.013534                 8.01,9.01     0
2         AA  2020-04-22  0.022930  0.008491  1.01,2.02,2.03,8.01,9.01     1
3         AA  2020-05-11  0.000133 -0.037308                      5.07     0
4         AA  2020-06-25  0.010959  0.050980            1.01,2.03,9.01     0
...      ...         ...       ...       ...                       ...   ...
25100     ZI  2022-05-02  0.005675  0.032299                 2.02,9.01     1
25101     ZI  2022-05-19 -0.005834 -0.021573       3.03,5.03,5.07,9.01     0
25102     ZI  2022-06-30 -0.008759 -0.019027            5.02,7.01,9.01     0
25103     ZI  2022-08-01 -0.002823 -0.001400                 2.02,9.01     1
25104     ZI  2022-11-01 -0.004101 -0.019029                 2.02,9.01     1

       9.01  8.01  1.01  2.03  ...  5.04  5.08  7.01104  5.01  1.03  6.01  \
0         1     0     0     0  ...     0     0        0     0     0     0
1         1     1     0     0  ...     0     0        0     0     0     0
2         1     1     1     1  ...     0     0        0     0     0     0
3         0     0     0     0  ...     0     0        0     0     0     0
4         1     0     1     1  ...     0     0        0     0     0     0
...     ...   ...   ...   ...  ...   ...   ...      ...   ...   ...   ...
25100     1     0     0     0  ...     0     0        0     0     0     0
25101     1     0     0     0  ...     0     0        0     0     0     0
25102     1     0     0     0  ...     0     0        0     0     0     0
25103     1     0     0     0  ...     0     0        0     0     0     0
25104     1     0     0     0  ...     0     0        0     0     0     0

       9.09  5.06  2.02101  2.02104
0         0     0        0        0
1         0     0        0        0
2         0     0        0        0
3         0     0        0        0
4         0     0        0        0
...     ...   ...      ...      ...
25100     0     0        0        0
25101     0     0        0        0
25102     0     0        0        0
25103     0     0        0        0
25104     0     0        0        0

[25105 rows x 36 columns]

In [5]:
import pandas as pd
from datetime import timedelta


# 将 'Filing Date' 列转换为日期时间格式
filtered_data['Filing Date'] = pd.to_datetime(filtered_data['Filing Date'])

# 按照 'Ticker' 列对数据进行分组，然后按 'Filing Date' 列升序排序
filtered_data = filtered_data.sort_values(by=['Ticker', 'Filing Date'])

# 创建一个字典来存储上一个 Section 的内容
prev_section = {}

# 遍历每行数据，将上一列的 'Section' 内容添加到本列的 'LSM' 项目中并将相应的列值设为1
for index, row in filtered_data.iterrows():
    ticker = row['Ticker']
    if ticker in prev_section and row['Filing Date'] - prev_section[ticker]['Filing Date'] <= timedelta(days=30):
        sections = prev_section[ticker]['Items'].split(',')
        for section in sections:
            column_name = 'LSM' + section
            filtered_data.at[index, column_name] = 1

    # 更新字典中的值
    prev_section[ticker] = row

    
# 将NaN替换为0
filtered_data = filtered_data.fillna(0)

# 打印筛选后的数据（包括新创建的列）
print(filtered_data)

      Ticker Filing Date    Market       Ret                     Items  2.02  \
0         AA  2020-01-15  0.001870 -0.011198                 2.02,9.01     1
1         AA  2020-02-03  0.007255  0.013534                 8.01,9.01     0
2         AA  2020-04-22  0.022930  0.008491  1.01,2.02,2.03,8.01,9.01     1
3         AA  2020-05-11  0.000133 -0.037308                      5.07     0
4         AA  2020-06-25  0.010959  0.050980            1.01,2.03,9.01     0
...      ...         ...       ...       ...                       ...   ...
25100     ZI  2022-05-02  0.005675  0.032299                 2.02,9.01     1
25101     ZI  2022-05-19 -0.005834 -0.021573       3.03,5.03,5.07,9.01     0
25102     ZI  2022-06-30 -0.008759 -0.019027            5.02,7.01,9.01     0
25103     ZI  2022-08-01 -0.002823 -0.001400                 2.02,9.01     1
25104     ZI  2022-11-01 -0.004101 -0.019029                 2.02,9.01     1

       9.01  8.01  1.01  2.03  ...  LSM5.04  LSM2.06  LSM5.08  LSM7.01104  \
0         1     0     0     0  ...      0.0      0.0      0.0         0.0
1         1     1     0     0  ...      0.0      0.0      0.0         0.0
2         1     1     1     1  ...      0.0      0.0      0.0         0.0
3         0     0     0     0  ...      0.0      0.0      0.0         0.0
4         1     0     1     1  ...      0.0      0.0      0.0         0.0
...     ...   ...   ...   ...  ...      ...      ...      ...         ...
25100     1     0     0     0  ...      0.0      0.0      0.0         0.0
25101     1     0     0     0  ...      0.0      0.0      0.0         0.0
25102     1     0     0     0  ...      0.0      0.0      0.0         0.0
25103     1     0     0     0  ...      0.0      0.0      0.0         0.0
25104     1     0     0     0  ...      0.0      0.0      0.0         0.0

       LSM3.01  LSM5.01  LSM1.03  LSM5.06  LSM2.02101  LSM2.02104
0          0.0      0.0      0.0      0.0         0.0         0.0
1          0.0      0.0      0.0      0.0         0.0         0.0
2          0.0      0.0      0.0      0.0         0.0         0.0
3          0.0      0.0      0.0      0.0         0.0         0.0
4          0.0      0.0      0.0      0.0         0.0         0.0
...        ...      ...      ...      ...         ...         ...
25100      0.0      0.0      0.0      0.0         0.0         0.0
25101      0.0      0.0      0.0      0.0         0.0         0.0
25102      0.0      0.0      0.0      0.0         0.0         0.0
25103      0.0      0.0      0.0      0.0         0.0         0.0
25104      0.0      0.0      0.0      0.0         0.0         0.0

[25105 rows x 65 columns]

In [6]:
filtered_data

,Ticker,Filing Date,Market,Ret,Items,2.02,9.01,8.01,1.01,2.03,...,LSM5.04,LSM2.06,LSM5.08,LSM7.01104,LSM3.01,LSM5.01,LSM1.03,LSM5.06,LSM2.02101,LSM2.02104
0,AA,2020-01-15,0.001870,-0.011198,"2.02,9.01",1,1,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,AA,2020-02-03,0.007255,0.013534,"8.01,9.01",0,1,1,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,AA,2020-04-22,0.022930,0.008491,"1.01,2.02,2.03,8.01,9.01",1,1,1,1,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,AA,2020-05-11,0.000133,-0.037308,5.07,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,AA,2020-06-25,0.010959,0.050980,"1.01,2.03,9.01",0,1,0,1,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25100,ZI,2022-05-02,0.005675,0.032299,"2.02,9.01",1,1,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
25101,ZI,2022-05-19,-0.005834,-0.021573,"3.03,5.03,5.07,9.01",0,1,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
25102,ZI,2022-06-30,-0.008759,-0.019027,"5.02,7.01,9.01",0,1,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
25103,ZI,2022-08-01,-0.002823,-0.001400,"2.02,9.01",1,1,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
25104,ZI,2022-11-01,-0.004101,-0.019029,"2.02,9.01",1,1,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [7]:
# 将 filtered_data 输出为 CSV 文件
filtered_data.to_csv('filtered_data.csv', index=False)